kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: test30
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue
  mode: all
  action: delay
  duration: 10m
  delay:
    latency: 3.0s
    correlation: '100'
    jitter: '0'
  direction: to
  target:
    selector:
      namespaces:
        - sock-shop
      labelSelectors:
        name: front-end
    mode: all

